package forme.klijent;

import forme.admin.FAdmin;
import java.awt.Color;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import poslovnalogika.Kontroler;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Megi
 */
public class FKlijentLogin extends javax.swing.JFrame {

    private static int brojPorta;
    private static String adresaServera;

    /**
     * Creates new form FKlijent
     */
    public FKlijentLogin() {

        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtKorisnickoIme = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtSifra = new javax.swing.JPasswordField();
        jbtnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jbtnRegistracija = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtIP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtPort = new javax.swing.JTextField();
        jlblServerStatus = new javax.swing.JLabel();
        jbtnPovezivanje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prijavljivanje klijenta");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Prijavljivanje");

        jLabel4.setText("Korisničko ime:");

        jtxtKorisnickoIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtKorisnickoImeActionPerformed(evt);
            }
        });

        jLabel5.setText("Korisnička šifra:");

        jbtnLogin.setText("Log in");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });

        jLabel3.setText("Nemaš nalog?");

        jbtnRegistracija.setText("Registruj se!");
        jbtnRegistracija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistracijaActionPerformed(evt);
            }
        });

        jLabel1.setText("IP adresa servera:");

        jLabel6.setText("Broj porta:");

        jlblServerStatus.setForeground(new java.awt.Color(255, 0, 0));
        jlblServerStatus.setText("Niste povezani na server!");

        jbtnPovezivanje.setText("Poveži se sa serverom");
        jbtnPovezivanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPovezivanjeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(jbtnLogin))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtxtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jtxtIP)
                                            .addComponent(jtxtPort))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jbtnRegistracija)
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jlblServerStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnPovezivanje)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblServerStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPovezivanje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnLogin)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnRegistracija)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel4))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtKorisnickoImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtKorisnickoImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtKorisnickoImeActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed

        String korisnickoIme = jtxtKorisnickoIme.getText().trim();
        String korisnickaSifra = new String(jtxtSifra.getPassword());

        try {

            if (Kontroler.getInstance().ulogujSe(korisnickoIme, korisnickaSifra)) {
                JOptionPane.showMessageDialog(this, "Klijent je uspešno prijavljen");
                if (korisnickoIme.equals("admin")) {
                    FAdmin g = new FAdmin();
                    g.setVisible(true);
                    this.dispose();
                } else {
                    FRezervacija rezervacija = new FRezervacija();

                    rezervacija.setVisible(true);
                    this.setVisible(false);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Sistem ne može da nađe klijenta na osnovu unetih vrednosti", "Greška", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe klijenta na osnovu unetih vrednosti" + ex.getMessage(),
                    "Greska", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jbtnRegistracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistracijaActionPerformed
        FRegistracija registracijaForma = new FRegistracija();
        registracijaForma.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnRegistracijaActionPerformed

    private void jbtnPovezivanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPovezivanjeActionPerformed
        Socket socket = null;
        try {
            adresaServera = jtxtIP.getText().trim();
            String sBrPorta = jtxtPort.getText().trim();
            Kontroler.getInstance().validirajIPAdresu(adresaServera);
            brojPorta = Kontroler.getInstance().validirajBrojPorta(sBrPorta);
            socket = new Socket(adresaServera, brojPorta);
            Kontroler.getInstance().setSocket(socket);

            jlblServerStatus.setText("Uspesno ste se povezali na server!");
            jlblServerStatus.setForeground(Color.GREEN);
            Kontroler.getInstance().setPovezanNaServer(true);

            jbtnLogin.setEnabled(true);
            jbtnRegistracija.setEnabled(true);
        } catch (IOException ex) {
            Logger.getLogger(FKlijentLogin.class.getName()).log(Level.SEVERE, null, ex);
            return;
        } catch (Exception ex) {
            Logger.getLogger(FKlijentLogin.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jbtnPovezivanjeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FKlijentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FKlijentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FKlijentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FKlijentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FKlijentLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnPovezivanje;
    private javax.swing.JButton jbtnRegistracija;
    private javax.swing.JLabel jlblServerStatus;
    private javax.swing.JTextField jtxtIP;
    private javax.swing.JTextField jtxtKorisnickoIme;
    private javax.swing.JTextField jtxtPort;
    private javax.swing.JPasswordField jtxtSifra;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        if (!Kontroler.getInstance().isPovezanNaServer()) {
            jbtnLogin.setEnabled(false);
            jbtnRegistracija.setEnabled(false);
        } else {
            jlblServerStatus.setText("Uspesno ste se povezali na server!");
            jlblServerStatus.setForeground(Color.GREEN);
            jbtnPovezivanje.setEnabled(false);
        }
    }
}
