/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.t;

import domen.GenerickiDomenskiObjekat;
import domen.Preparat;
import domen.Tretman;
import domen.TretmanPreparati;
import gui.modeltabele.PreparatModelTabele;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import poslovnalogika.Kontroler;

/**
 *
 * @author Megi
 */
public class FDetalji extends javax.swing.JFrame {

    private List<TretmanPreparati> listaDesno;
    private List<Preparat> listaLevo;
    List<Preparat> listaPreparata;
    private PreparatModelTabele pmt;
    private DefaultListModel<Preparat> dlm;
    private ArrayList<Preparat> lp;
    private int tretmanID;

    /**
     * Creates new form FDetalji
     */
    public FDetalji() throws ClassNotFoundException, SQLException, IOException, Exception {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblPreparati = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListIzabraniPreparati = new javax.swing.JList();
        jbtnDodajPreparat = new javax.swing.JButton();
        jbtnObrisiPreparat = new javax.swing.JButton();
        jbtnSacuvaj = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        errIzbor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Preostali preparati:");

        jLabel3.setText("Izabrani preparati:");

        jtblPreparati.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtblPreparati);

        jScrollPane4.setViewportView(jListIzabraniPreparati);

        jbtnDodajPreparat.setText("->");
        jbtnDodajPreparat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajPreparatActionPerformed(evt);
            }
        });

        jbtnObrisiPreparat.setText("<-");
        jbtnObrisiPreparat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiPreparatActionPerformed(evt);
            }
        });

        jbtnSacuvaj.setText("Sačuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jButton3.setText("Izlaz");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        errIzbor.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnSacuvaj)
                    .addComponent(errIzbor, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnDodajPreparat)
                            .addComponent(jbtnObrisiPreparat))
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(51, 51, 51))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(390, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jbtnDodajPreparat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnObrisiPreparat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(errIzbor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSacuvaj)
                    .addComponent(jButton3))
                .addGap(58, 58, 58))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel4)
                    .addGap(13, 13, 13)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(158, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDodajPreparatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajPreparatActionPerformed
        errIzbor.setText("");
        if (!listaLevo.isEmpty() && jtblPreparati.getSelectedRow() > -1) {
            listaPreparata.add((Preparat) listaLevo.get(jtblPreparati.getSelectedRow()));
            listaLevo.remove(jtblPreparati.getSelectedRow());
            pmt = new PreparatModelTabele(listaLevo);
            jtblPreparati.setModel(pmt);
            dlm = new DefaultListModel<Preparat>();
            for (GenerickiDomenskiObjekat p : listaPreparata) {
                dlm.addElement((Preparat) p);
            }
            jListIzabraniPreparati.setModel(dlm);
        } else {
            errIzbor.setText("Morate izabrati preparat koji želite da dodate!");
        }
    }//GEN-LAST:event_jbtnDodajPreparatActionPerformed

    private void jbtnObrisiPreparatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiPreparatActionPerformed
        errIzbor.setText("");
        if (!listaPreparata.isEmpty() && jListIzabraniPreparati.getSelectedIndex() > -1) {
            listaLevo.add(listaPreparata.get(jListIzabraniPreparati.getSelectedIndex()));
            listaPreparata.remove(jListIzabraniPreparati.getSelectedIndex());
            pmt = new PreparatModelTabele(listaLevo);
            jtblPreparati.setModel(pmt);
            dlm = new DefaultListModel<Preparat>();
            for (GenerickiDomenskiObjekat p : listaPreparata) {
                dlm.addElement((Preparat) p);
            }
            jListIzabraniPreparati.setModel(dlm);
        }
        else {
            errIzbor.setText("Morate izabrati preparat koji želite da uklonite!");
        }
    }//GEN-LAST:event_jbtnObrisiPreparatActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed

        boolean validacija = true;

        lp = new ArrayList<Preparat>();
        List<TretmanPreparati> ltp = new ArrayList<>();

        ListModel model = jListIzabraniPreparati.getModel();
        for (int i = 0; i < model.getSize(); i++) {
            Preparat p = (Preparat) model.getElementAt(i);
            lp.add(p);
            ltp.add(new TretmanPreparati(tretmanID, p.getPreparatID()));
        }

        try {
            Tretman t = new Tretman(tretmanID);
            Kontroler.getInstance().obrisiPreparateTretmana(t);
            JOptionPane.showMessageDialog(this, "Obrisani su preparati tretmana...");

            Kontroler.getInstance().setListaPreparataTretmana(ltp);
            Kontroler.getInstance().dodajPreparateTretmana();
            JOptionPane.showMessageDialog(this, "Uspesno su dodati preparati tretmana!");
            JOptionPane.showMessageDialog(this, "Tretman je uspešno sačuvan");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Nije moguće sačuvati podatke o tretmanu", "Greška", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FDetalji.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FDetalji.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FDetalji.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FDetalji.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FDetalji().setVisible(true);

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FDetalji.class
                            .getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(FDetalji.class
                            .getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(FDetalji.class
                            .getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(FDetalji.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errIzbor;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jListIzabraniPreparati;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbtnDodajPreparat;
    private javax.swing.JButton jbtnObrisiPreparat;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JTable jtblPreparati;
    // End of variables declaration//GEN-END:variables

    public int getTretmanID() {
        return tretmanID;
    }

    public void setTretmanID(int tretmanID) {
        this.tretmanID = tretmanID;
    }

    public void srediFormu() throws ClassNotFoundException, SQLException, IOException, Exception {

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        Tretman t = new Tretman(tretmanID);
        try {
            listaDesno = Kontroler.getInstance().vratiSvePreparateTretmana(t);
            listaPreparata = new ArrayList<>();

            DefaultListModel dlm = new DefaultListModel();
            for (int i = 0; i < listaDesno.size(); i++) {
                Preparat p1 = new Preparat();
                p1.setPreparatID(((TretmanPreparati) listaDesno.get(i)).getPreparatID());
                Preparat p = Kontroler.getInstance().vratiPreparatPoID(p1);
                dlm.addElement(p);
                listaPreparata.add(p);
                jListIzabraniPreparati.setModel(dlm);

                listaLevo = Kontroler.getInstance().vratiSvePreparate();
                for (int k = 0; k < listaLevo.size(); k++) {
                    for (int j = 0; j < listaPreparata.size(); j++) {
                        if (listaLevo.get(k).equals(listaPreparata.get(j))) {
                            listaLevo.remove(k);
                        }
                    }
                }

                PreparatModelTabele pmt = new PreparatModelTabele(listaLevo);
                jtblPreparati.setModel(pmt);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }

    }

}
