
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.t;

import domen.GenerickiDomenskiObjekat;
import domen.Preparat;
import domen.Tretman;
import domen.TretmanPreparati;
import gui.modeltabele.PreparatModelTabele;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import poslovnalogika.Kontroler;
import protokol.objekti.KlijentZahtev;
import protokol.objekti.ServerOdgovor;

/**
 *
 * @author student1
 */
public class FTretman extends javax.swing.JFrame {

    DefaultListModel<Preparat> dlm;
    ArrayList<Preparat> lp;
    List<Preparat> lpRef;
    PreparatModelTabele pmt;
    List<Preparat> lista;
    List<Preparat> listaLevo;
    private List<Preparat> listaDesno;
    private Tretman tretmanIzmena;

    public FTretman() {
        initComponents();
        try {
            srediFormu();
        } catch (Exception ex) {
            Logger.getLogger(FTretman.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbtnSacuvaj = new javax.swing.JButton();
        jtxtOpis = new javax.swing.JTextField();
        jtxtTrajanje = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        errDatum = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblPreparati = new javax.swing.JTable();
        jbtnObrisiPreparat = new javax.swing.JButton();
        jbtnDodajPreparat = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListIzabraniPreparati = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos tretmana");

        jLabel1.setText("Opis tretmana:");

        jbtnSacuvaj.setText("Sačuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jtxtTrajanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTrajanjeActionPerformed(evt);
            }
        });

        jLabel5.setText("Trajanje u minutima:");

        errDatum.setForeground(new java.awt.Color(255, 0, 0));

        jtblPreparati.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtblPreparati);

        jbtnObrisiPreparat.setText("<-");
        jbtnObrisiPreparat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiPreparatActionPerformed(evt);
            }
        });

        jbtnDodajPreparat.setText("->");
        jbtnDodajPreparat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajPreparatActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(jListIzabraniPreparati);

        jLabel3.setText("Izabrani preparati:");

        jLabel4.setText("Svi preparati:");

        jButton3.setText("Izlaz");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(errDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtOpis, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnObrisiPreparat)
                            .addComponent(jbtnDodajPreparat))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(jbtnSacuvaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtOpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jbtnDodajPreparat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jbtnObrisiPreparat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSacuvaj)
                    .addComponent(jButton3))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed

        String opis = jtxtOpis.getText().trim();
        String trajanje = jtxtTrajanje.getText().trim();
        double cena = 0;
        boolean validacija = true;

        if (opis == null || opis.equals("") || trajanje == null || trajanje.equals("")) {
            validacija = false;
        }

        if (validacija == true) {
            Tretman t = new Tretman();
            t.setOpis(opis);
            t.setTrajanjeUMin(Integer.parseInt(trajanje));

            lp = new ArrayList<Preparat>();

            ListModel model = jListIzabraniPreparati.getModel();
            for (int i = 0; i < model.getSize(); i++) {
                Preparat p = (Preparat) model.getElementAt(i);
                lp.add(p);
                cena += p.getCena();
            }
            t.setCena(cena);
            t.setListaPreparata(lp); //da li je potrebno?

            List<TretmanPreparati> preparatiTretmana = new ArrayList<>();

            try {

                int tretmanID = Kontroler.getInstance().dodajTretman(t);
                JOptionPane.showMessageDialog(this, "Tretman je uspešno dodat.");

                for (Preparat p : lp) {
                    preparatiTretmana.add(new TretmanPreparati(tretmanID, p.getPreparatID()));
                }
                Kontroler.getInstance().setListaPreparataTretmana(preparatiTretmana);
                Kontroler.getInstance().dodajPreparateTretmana();

              //  JOptionPane.showMessageDialog(this, "Uspesno dodati preparati tretmana!");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da kreira novi tretman", "Greska", JOptionPane.ERROR_MESSAGE);
            }

            try {
                resetujFormu();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da kreira novi tretman", "Greska", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Morate popuniti sva polja!");

        }

    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jtxtTrajanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTrajanjeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTrajanjeActionPerformed

    private void jbtnObrisiPreparatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiPreparatActionPerformed
        if (jListIzabraniPreparati.getSelectedIndex() != -1) {
            listaLevo.add(listaDesno.get(jListIzabraniPreparati.getSelectedIndex()));
            listaDesno.remove(jListIzabraniPreparati.getSelectedIndex());
            pmt = new PreparatModelTabele(listaLevo);
            jtblPreparati.setModel(pmt);
            dlm = new DefaultListModel<Preparat>();
            for (GenerickiDomenskiObjekat p : listaDesno) {
                dlm.addElement((Preparat) p);
            }
            jListIzabraniPreparati.setModel(dlm);
        } else {
            JOptionPane.showMessageDialog(getParent(), "Morate odabrati preparat!");
        }
    }//GEN-LAST:event_jbtnObrisiPreparatActionPerformed

    private void jbtnDodajPreparatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajPreparatActionPerformed
        if (jtblPreparati.getSelectedRow() != -1) {
            listaDesno.add(listaLevo.get(jtblPreparati.getSelectedRow()));
            listaLevo.remove(jtblPreparati.getSelectedRow());
            pmt = new PreparatModelTabele(listaLevo);
            jtblPreparati.setModel(pmt);
            dlm = new DefaultListModel<Preparat>();
            for (GenerickiDomenskiObjekat p : listaDesno) {
                dlm.addElement((Preparat) p);
            }
            jListIzabraniPreparati.setModel(dlm);
        } else {
            JOptionPane.showMessageDialog(getParent(), "Morate odabrati preparat!");
        }
    }//GEN-LAST:event_jbtnDodajPreparatActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTretman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTretman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTretman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTretman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTretman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errDatum;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jListIzabraniPreparati;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbtnDodajPreparat;
    private javax.swing.JButton jbtnObrisiPreparat;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JTable jtblPreparati;
    private javax.swing.JTextField jtxtOpis;
    private javax.swing.JTextField jtxtTrajanje;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() throws ClassNotFoundException, SQLException, IOException, Exception {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        try {
            lista = new ArrayList<Preparat>();
            listaLevo = Kontroler.getInstance().vratiSvePreparate();
            pmt = new PreparatModelTabele(listaLevo);
            jtblPreparati.setModel(pmt);

            listaDesno = new ArrayList<Preparat>();
            dlm = new DefaultListModel();
            jListIzabraniPreparati.setModel(dlm);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex, "Greska", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void resetujFormu() throws ClassNotFoundException, SQLException, IOException, Exception {
        jtxtOpis.setText("");
        jtxtTrajanje.setText("");      
        errDatum.setText("");

        try {
            listaLevo = new ArrayList<Preparat>(Kontroler.getInstance().vratiSvePreparate());

            pmt = new PreparatModelTabele(listaLevo);
            jtblPreparati.setModel(pmt);

            listaDesno = new ArrayList<Preparat>();
            dlm = new DefaultListModel();
            jListIzabraniPreparati.setModel(dlm);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex, "Greska", JOptionPane.ERROR_MESSAGE);
        }

    }
}
